from app.models import db, Card


# Adds a demo user, you can add other users here if you want
def seed_cards():
    card001 = Card(deckId=1, question="yes (I agree)", answer="네 (ne)" )
    card002 = Card(deckId=1, question="no", answer="아니요 (aniyo)" )
    card003 = Card(deckId=1, question="what? (pardon me?, say again?)", answer="네? (ne?)" )
    card004 = Card(deckId=1, question="that's right", answer="맞아요 (majayo)" )
    card005 = Card(deckId=1, question="thank you", answer="감사합니다 (gam-sa-hab-ni-da)" )
    card006 = Card(deckId=1, question="hello (formal)", answer="안녕하세요 (an-nyeong-ha-se-yo)" )
    card007 = Card(deckId=1, question="hi (informal)", answer="안녕 (an-nyeong)" )
    card008 = Card(deckId=1, question="welcome", answer="어서오세요 [eo-seo-o-se-yo]" )
    card009 = Card(deckId=1, question="goodbye (staying - formal)", answer="안녕히 가세요 (an-nyeong-hi ga-se-yo)" )
    card010 = Card(deckId=1, question="goodbye (departing - formal)", answer="안녕히 계세요 (an-nyeong-hi gye-se-yo)" )
    card011 = Card(deckId=1, question="goodnight (formal)", answer="안녕히 주무세요 [an-nyeong-hi ju-mu-se-yo]" )
    card012 = Card(deckId=1, question="I'm sorry (formal)", answer="죄송합니다 (joe-song-hap-mi-da)" )
    card013 = Card(deckId=1, question="excuse me (hey you, your attention please)", answer="저기요 (jeo-gi-yo)" )
    card014 = Card(deckId=1, question="excuse me (just a moment, pardon me (while passing through a crowd))", answer="잠시만요 (jam-si-man-yo)" )

    card015 = Card(deckId=2, question="Good morning", answer="おはようございます" )
    card016 = Card(deckId=2, question="Hello or good afternoon", answer="こんにちは" )
    card017 = Card(deckId=2, question="Good evening", answer="こんばんは" )
    card018 = Card(deckId=2, question="Good night", answer="おやすみなさい" )
    card019 = Card(deckId=2, question="See you again", answer="ではまた" )
    card020 = Card(deckId=2, question="Goodbye", answer="さようなら" )
    card021 = Card(deckId=2, question="Goodbye (being said who's staying at home)", answer="いってきます" )
    card022 = Card(deckId=2, question="Goodbye (being said who's departing)", answer="いってらっしゃい" )
    card023 = Card(deckId=2, question="I'm home or I'm back", answer="ただいま" )
    card024 = Card(deckId=2, question="Welcome home", answer="おかえりなさい" )
    card025 = Card(deckId=2, question="Congratulation", answer="おめでとうございます" )
    card026 = Card(deckId=2, question="Thank you very much", answer="どうも ありがとうございます" )
    card027 = Card(deckId=2, question="You're welcome", answer="どういたしまして" )
    card028 = Card(deckId=2, question="I'll be leaving ahead", answer="おさき に しつれい します" )
    card029 = Card(deckId=2, question="Thank you for your hard work", answer="おつかれ さま でした" )
    card030 = Card(deckId=2, question="Take care", answer="きを つけて" )
    card031 = Card(deckId=2, question="Thank you (start of meal)", answer="いただきます" )
    card032 = Card(deckId=2, question="Thank you (after meal)", answer="ごちそうさま でした" )
    card033 = Card(deckId=2, question="Look after yourself", answer="おげんき で" )
    card034 = Card(deckId=2, question="Is there anybody in?", answer="ごめん ください" )
    card035 = Card(deckId=2, question="Excuse me (entering the room)", answer="しつれい します" )
    card036 = Card(deckId=2, question="How are you?", answer="お げんき ですか" )
    card037 = Card(deckId=2, question="No problem", answer="だいじょうぶ です" )
    card038 = Card(deckId=2, question="Excuse me", answer="すみません" )
    card039 = Card(deckId=2, question="I'm sorry", answer="ごめんなさい" )
    card040 = Card(deckId=2, question="Attention", answer="き を つけ!" )
    card041 = Card(deckId=2, question="Greetings", answer="あいさつのことば" )

    card042 = Card(deckId=3, question="Hello/Hi", answer="Hola" )
    card043 = Card(deckId=3, question="good morning, good day", answer="Buenos días" )
    card044 = Card(deckId=3, question="Good afternoon", answer="Buenas tardes" )
    card045 = Card(deckId=3, question="Good evening, good night", answer="Buenas noches" )
    card046 = Card(deckId=3, question="The pleasure is mine", answer="El gusto es mío" )
    card047 = Card(deckId=3, question="delighted", answer="Encantado/Encantada" )
    card048 = Card(deckId=3, question="It's a pleasure", answer="Es un placer" )
    card049 = Card(deckId=3, question="Likewise", answer="Iqualmente" )
    card050 = Card(deckId=3, question="Pleased/Nice to meet you.", answer="Mucho gusto" )
    card051 = Card(deckId=3, question="and you (familiar, informal)", answer="Y tú" )
    card052 = Card(deckId=3, question="Goodbye", answer="Adiós" )
    card053 = Card(deckId=3, question="See you later", answer="Hasta luego" )
    card054 = Card(deckId=3, question="See you tomorrow", answer="Hasta mañana" )
    card055 = Card(deckId=3, question="See you", answer="Nos vemos" )
    card056 = Card(deckId=3, question="last name", answer="el appellido" )
    card057 = Card(deckId=3, question="name", answer="el nombre" )
    card058 = Card(deckId=3, question="What's your name? (familiar)", answer="¿Cómo te llamas?" )
    card059 = Card(deckId=3, question="What's his/her/your (formal) name?", answer="¿Cómo se llama?" )
    card060 = Card(deckId=3, question="My name is ...", answer="Me llamo" )
    card061 = Card(deckId=3, question="His / Her name is . . .", answer="Se llama" )
    card062 = Card(deckId=3, question="How are you? (familiar)", answer="¿Cómo estás?" )
    card063 = Card(deckId=3, question="How are you? (formal)", answer="¿ Cómo está usted?" )
    card064 = Card(deckId=3, question="I am", answer="estoy" )
    card065 = Card(deckId=3, question="fine", answer="bien" )
    card066 = Card(deckId=3, question="very well", answer="Muy bien" )
    card067 = Card(deckId=3, question="good", answer="bueno/a" )
    card068 = Card(deckId=3, question="bad", answer="malo/a" )
    card069 = Card(deckId=3, question="very bad", answer="muy mal" )
    card070 = Card(deckId=3, question="Not very well", answer="No muy bien" )

    card071 = Card(deckId=4, question="Hello (nǐ hǎo)", answer="你好" )
    card072 = Card(deckId=4, question="you (nǐ)", answer="你" )
    card073 = Card(deckId=4, question="good (hǎo)", answer="好" )
    card074 = Card(deckId=4, question="you formal (nín)", answer="您" )
    card075 = Card(deckId=4, question="zǎo - morning, early", answer="早" )
    card076 = Card(deckId=4, question="nǐ zǎo - good morning", answer="你早" )
    card077 = Card(deckId=4, question="(zài) again", answer="再" )
    card078 = Card(deckId=4, question="(jiàn) to see", answer="见" )
    card079 = Card(deckId=4, question="zài jiàn - goodbye", answer="再见" )
    card080 = Card(deckId=4, question="ma - question word", answer="吗" )
    card081 = Card(deckId=4, question="How are you? (nǐ hăo ma)", answer="你好吗？" )
    card082 = Card(deckId=4, question="no, not (bù)", answer="不" )
    card083 = Card(deckId=4, question="cuò - wrong, bad", answer="错" )
    card084 = Card(deckId=4, question="not bad (búcuò)", answer="不错" )
    card085 = Card(deckId=4, question="hái - also", answer="还" )
    card086 = Card(deckId=4, question="can (kě)", answer="可" )
    card087 = Card(deckId=4, question="yǐ - use, by, for", answer="以" )
    card088 = Card(deckId=4, question="can - Pretty good (kê yî)", answer="可以" )
    card089 = Card(deckId=4, question="hái kěyĭ - not bad, OK", answer="还可以" )
    card090 = Card(deckId=4, question="wǒ - I, me", answer="我" )
    card091 = Card(deckId=4, question="hěn - very", answer="很" )
    card092 = Card(deckId=4, question="hěn hǎo - very good", answer="很好" )
    card093 = Card(deckId=4, question="thank you (xièxie)", answer="谢谢" )
    card094 = Card(deckId=4, question="ne (question particle for subjects already mentioned)", answer="呢" )
    card095 = Card(deckId=4, question="nǐ ne - how about you", answer="你呢" )
    card096 = Card(deckId=4, question="yě - also, too", answer="也" )
    card097 = Card(deckId=4, question="to be (shì)", answer="是" )
    card098 = Card(deckId=4, question="de - (a possessive particle used after pronoun/noun)", answer="的" )
    card099 = Card(deckId=4, question="wǒ de - my, mine", answer="我的" )
    card100 = Card(deckId=4, question="péng - friend", answer="朋" )
    card101 = Card(deckId=4, question="yǒu - friend", answer="友" )
    card102 = Card(deckId=4, question="péng you - friend", answer="朋友" )
    card103 = Card(deckId=4, question="yī - one", answer="一" )
    card104 = Card(deckId=4, question="èr - two", answer="二" )
    card105 = Card(deckId=4, question="sān - three", answer="三" )
    card106 = Card(deckId=4, question="sì - four", answer="四" )
    card107 = Card(deckId=4, question="wǔ - five", answer="五" )
    card108 = Card(deckId=4, question="liù - six", answer="六" )
    card109 = Card(deckId=4, question="qī - seven", answer="七" )
    card110 = Card(deckId=4, question="bā - eight", answer="八" )
    card111 = Card(deckId=4, question="jiǔ - nine", answer="九" )
    card112 = Card(deckId=4, question="shí - ten", answer="十" )
    card113 = Card(deckId=4, question="your", answer="你的" )
    card114 = Card(deckId=4, question="my, mine", answer="我的" )
    card115 = Card(deckId=4, question="friend's", answer="朋友的" )
    card116 = Card(deckId=4, question="My good friend", answer="我的好朋友的" )
    card117 = Card(deckId=4, question="today; now (jīn)", answer="今" )
    card118 = Card(deckId=4, question="tiān - day", answer="天" )
    card119 = Card(deckId=4, question="jǐ - how many", answer="几" )
    card120 = Card(deckId=4, question="yuè - month; the moon", answer="月" )
    card121 = Card(deckId=4, question="which month (jǐ yuè)", answer="几月" )
    card122 = Card(deckId=4, question="number (hào) date", answer="号" )
    card123 = Card(deckId=4, question="what date (jǐ hào)", answer="几号" )
    card124 = Card(deckId=4, question="xīng - star", answer="星" )
    card125 = Card(deckId=4, question="a period of time (qī)", answer="期" )
    card126 = Card(deckId=4, question="week (xīngqī)", answer="星期" )
    card127 = Card(deckId=4, question="What day of the week?", answer="星期几？" )
    card128 = Card(deckId=4, question="zuó - yesterday", answer="昨" )
    card129 = Card(deckId=4, question="zuó tiān - yesterday", answer="昨天" )
    card130 = Card(deckId=4, question="rì - day; the sun", answer="日" )
    card131 = Card(deckId=4, question="bright (míng)", answer="明" )
    card132 = Card(deckId=4, question="míng tiān - tomorrow", answer="明天" )
    card133 = Card(deckId=4, question="jiào - to be called, to call", answer="叫" )
    card134 = Card(deckId=4, question="shén me - what", answer="什么" )
    card135 = Card(deckId=4, question="name (míng)", answer="名" )
    card136 = Card(deckId=4, question="zì - character, word", answer="字" )
    card137 = Card(deckId=4, question="míng zi - given name", answer="名字" )
    card138 = Card(deckId=4, question="He/She", answer="他 她" )
    card139 = Card(deckId=4, question="zhù - to live", answer="住" )
    card140 = Card(deckId=4, question="zài - at, in, on", answer="在" )
    card141 = Card(deckId=4, question="nǎ - which", answer="哪" )
    card142 = Card(deckId=4, question="son (ér)", answer="儿" )
    card143 = Card(deckId=4, question="nǎr - where", answer="哪儿" )
    card144 = Card(deckId=4, question="medium; middle (zhōng)", answer="中" )
    card145 = Card(deckId=4, question="Country or Kingdom", answer="国 or 國" )
    card146 = Card(deckId=4, question="zhōng guó - China", answer="中国" )
    card147 = Card(deckId=4, question="rén - person", answer="人" )
    card148 = Card(deckId=4, question="Chinese person (zhōng guó rén)", answer="中国人" )
    card149 = Card(deckId=4, question="běi - north", answer="北" )
    card150 = Card(deckId=4, question="jīng - capital", answer="京" )
    card151 = Card(deckId=4, question="běi jīng - Beijing", answer="北京" )
    card152 = Card(deckId=4, question="up (shàng)", answer="上" )
    card153 = Card(deckId=4, question="sea (hǎi)", answer="海" )
    card154 = Card(deckId=4, question="(shànghǎi) Shanghai", answer="上海" )
    card155 = Card(deckId=4, question="(xī) west", answer="西" )
    card156 = Card(deckId=4, question="peaceful （an）", answer="安" )
    card157 = Card(deckId=4, question="Xi'an", answer="西安" )
    card158 = Card(deckId=4, question="root; origin (Bên)", answer="本" )
    card159 = Card(deckId=4, question="(rìběn) Japan", answer="日本" )
    card160 = Card(deckId=4, question="Japanese person (ri ben ren)", answer="日本人" )
    card161 = Card(deckId=4, question="xiāng - fragrant", answer="香" )
    card162 = Card(deckId=4, question="harbour 'gang'", answer="港" )
    card163 = Card(deckId=4, question="Hong Kong (Xiānggǎng)", answer="香港" )
    card164 = Card(deckId=4, question="(nǎ guó rén) which nationality?", answer="哪国人" )
    card165 = Card(deckId=4, question="Nǐ zhù zài nǎr? - Where do you live?", answer="你住在哪儿？" )
    card166 = Card(deckId=4, question="Where does he live?", answer="他住在哪儿？" )
    card167 = Card(deckId=4, question="What is your nationality?", answer="你是哪国人？(Nǐ shì nǎ guó rén?)" )
    card168 = Card(deckId=4, question="Where does she live?", answer="她住在哪儿？" )
    card169 = Card(deckId=4, question="I live in", answer="我住在" )
    card170 = Card(deckId=4, question="Who is he?", answer="他是谁？(tā shì shéi)" )
    card171 = Card(deckId=4, question="Who is she?", answer="她是谁？(tā shì shuí)" )
    card172 = Card(deckId=4, question="This is me", answer="这是我" )
    card173 = Card(deckId=4, question="Who is this?", answer="这是谁" )
    card174 = Card(deckId=4, question="zhè - this", answer="这" )
    card175 = Card(deckId=4, question="jiā - family, home", answer="家" )
    card176 = Card(deckId=4, question="one family (yì jiā rén)", answer="一家人" )
    card177 = Card(deckId=4, question="men (plural form)", answer="们" )
    card178 = Card(deckId=4, question="(tāmen) they, them", answer="他 们" )
    card179 = Card(deckId=4, question="(wǒmen) we; us", answer="我们" )
    card180 = Card(deckId=4, question="mum (māma)", answer="妈妈" )
    card181 = Card(deckId=4, question="younger sister (mèi mei)", answer="妹妹" )
    card182 = Card(deckId=4, question="younger brother (dì di)", answer="弟弟" )
    card183 = Card(deckId=4, question="bàba - dad, father", answer="爸爸" )
    card184 = Card(deckId=4, question="grandfather (father's side) (yéye)", answer="爷爷" )
    card185 = Card(deckId=4, question="grandmother (father's-side) nainai", answer="奶奶" )
    card186 = Card(deckId=4, question="shéi - who", answer="谁" )
    card187 = Card(deckId=4, question="(gēge) older brother", answer="哥哥" )
    card188 = Card(deckId=4, question="(jiějie) older sister", answer="姐姐" )
    card189 = Card(deckId=4, question="this is my。。。", answer="这是我的" )
    card190 = Card(deckId=4, question="Australian", answer="澳大利亚人" )
    card191 = Card(deckId=4, question="Australia (ào dà lì yà)", answer="澳大利亚" )
    card192 = Card(deckId=4, question="America (měi guó)", answer="美国" )
    card193 = Card(deckId=4, question="yǒu - to have, there is/are", answer="有" )
    card194 = Card(deckId=4, question="méi guó rén - American", answer="美国人" )
    card195 = Card(deckId=4, question="seven members in the family (qī kǒu rén)", answer="七口人" )
    card196 = Card(deckId=4, question="dà - big", answer="大" )
    card197 = Card(deckId=4, question="big younger brother (dà dì di)", answer="大弟弟" )
    card198 = Card(deckId=4, question="small (xiǎo)", answer="小" )
    card199 = Card(deckId=4, question="little younger brother", answer="小弟弟" )
    card200 = Card(deckId=4, question="nà - that", answer="那" )
    card201 = Card(deckId=4, question="gè - measure word", answer="个" )
    card202 = Card(deckId=4, question="one elder brother (yí ge gē ge)", answer="一个哥哥" )
    card203 = Card(deckId=4, question="liǎng - two", answer="两" )
    card204 = Card(deckId=4, question="two younger brothers (liǎng ge dì di)", answer="两个弟弟" )
    card205 = Card(deckId=4, question="hé - and", answer="和" )
    card206 = Card(deckId=4, question="hero", answer="英" )
    card207 = Card(deckId=4, question="Britain (yīng guó)", answer="英国" )
    card208 = Card(deckId=4, question="British people (yīng guó rén)", answer="英国人" )
    card209 = Card(deckId=4, question="how many (mw) family members ?(jǐ kǒu rén)", answer="几口人？" )
    card210 = Card(deckId=4, question="elder brother", answer="兄" )
    card211 = Card(deckId=4, question="xiōng dì jiě mèi - siblings", answer="兄弟姐妹" )
    card212 = Card(deckId=4, question="méi - not", answer="没" )
    card213 = Card(deckId=4, question="méi yǒu -- don't have, there is not", answer="没有" )
    card214 = Card(deckId=4, question="(gōng) labor; work", answer="工" )
    card215 = Card(deckId=4, question="to do （zuo）", answer="作" )
    card216 = Card(deckId=4, question="gōng zuò - work, to work", answer="工作" )
    card217 = Card(deckId=4, question="year (of age) (suì)", answer="岁" )
    card218 = Card(deckId=4, question="12 years old (shí èr suì)", answer="十二岁" )
    card219 = Card(deckId=4, question="grow （sheng）", answer="生" )
    card220 = Card(deckId=4, question="xué sheng - student", answer="学生" )
    card221 = Card(deckId=4, question="secondary school student", answer="中学生 zhōng xué shēng" )
    card222 = Card(deckId=4, question="primary school student", answer="小学生 (xiǎo xué shēng)" )
    card223 = Card(deckId=4, question="le - indicates past tense", answer="了" )
    card224 = Card(deckId=4, question="(jǐ suì) how old? For under 10s", answer="几岁" )
    card225 = Card(deckId=4, question="(duō dà) how old/ how big in size? For over tens", answer="多大" )
    card226 = Card(deckId=4, question="(Nǐ jǐ suì le?) How old are you?", answer="你几岁了？" )
    card227 = Card(deckId=4, question="How old are you? (nǐ duō dà le?)", answer="你多大了？" )
    card228 = Card(deckId=4, question="How old is he?", answer="他几岁了？" )
    card229 = Card(deckId=4, question="What is his nationality?", answer="他是哪国人？" )
    card230 = Card(deckId=4, question="Are you a secondary school student?", answer="你是中学生吗？" )
    card231 = Card(deckId=4, question="nián - year", answer="年" )
    card232 = Card(deckId=4, question="jīnnián - this year", answer="今年" )
    card233 = Card(deckId=4, question="grade (jí)", answer="级" )
    card234 = Card(deckId=4, question="grade", answer="年级" )
    card235 = Card(deckId=4, question="niánjí - grade", answer="年级" )
    card236 = Card(deckId=4, question="in Grade 5 shang wu nian ji", answer="上五年级" )
    card237 = Card(deckId=4, question="(dàgē) eldest brother", answer="大哥" )
    card238 = Card(deckId=4, question="university student （da xue sheng)", answer="大学生" )
    card239 = Card(deckId=4, question="second eldest brother, (èr gē)", answer="二哥" )
    card240 = Card(deckId=4, question="both; all (dōu)", answer="都" )
    card241 = Card(deckId=4, question="birthday", answer="shengri 生日" )
    card242 = Card(deckId=4, question="(jiā ná dà) Canada", answer="加拿大" )
    card243 = Card(deckId=4, question="France (fǎ guó)", answer="法国" )
    card244 = Card(deckId=4, question="Dé guó - Germany", answer="德国" )
    card245 = Card(deckId=4, question="mǎ lái xī yà - Malaysia", answer="马来西亚" )
    card246 = Card(deckId=4, question="South Africa (Nánfēi)", answer="南非" )
    card247 = Card(deckId=4, question="Ōu zhōu - Europe", answer="欧洲" )
    card248 = Card(deckId=4, question="yà zhōu - Asia", answer="亚洲" )
    card249 = Card(deckId=4, question="Fēi zhōu - Africa", answer="非洲" )
    card250 = Card(deckId=4, question="Brazil (bā xī)", answer="巴西" )

    card251 = Card(deckId=5, question="alpha", answer="Α" )
    card252 = Card(deckId=5, question="beta", answer="Β" )
    card253 = Card(deckId=5, question="gamma", answer="Γ" )
    card254 = Card(deckId=5, question="delta", answer="Δ" )
    card255 = Card(deckId=5, question="epsilon", answer="Ε" )
    card256 = Card(deckId=5, question="zeta", answer="Ζ" )
    card257 = Card(deckId=5, question="eta", answer="Η" )
    card258 = Card(deckId=5, question="theta", answer="Θ" )
    card259 = Card(deckId=5, question="iota", answer="Ι" )
    card260 = Card(deckId=5, question="kappa", answer="Κ" )
    card261 = Card(deckId=5, question="lambda", answer="Λ" )
    card262 = Card(deckId=5, question="mu", answer="Μ" )
    card263 = Card(deckId=5, question="nu", answer="Ν" )
    card264 = Card(deckId=5, question="xi", answer="Ξ" )
    card265 = Card(deckId=5, question="omicron", answer="Ο" )
    card266 = Card(deckId=5, question="pi", answer="Π" )
    card267 = Card(deckId=5, question="rho", answer="Ρ" )
    card268 = Card(deckId=5, question="sigma", answer="Σ" )
    card269 = Card(deckId=5, question="tau", answer="Τ" )
    card270 = Card(deckId=5, question="upsilon", answer="Υ" )
    card271 = Card(deckId=5, question="phi", answer="Φ" )
    card272 = Card(deckId=5, question="chi", answer="Χ" )
    card273 = Card(deckId=5, question="psi", answer="Ψ" )
    card274 = Card(deckId=5, question="omega", answer="Ω" )

    card275 = Card(deckId=6, question="mine", answer="Мой" )
    card276 = Card(deckId=6, question="when", answer="когда" )
    card277 = Card(deckId=6, question="good", answer="хорошо" )
    card278 = Card(deckId=6, question="forgot", answer="забыть" )
    card279 = Card(deckId=6, question="neighbor", answer="сосед" )
    card280 = Card(deckId=6, question="friend", answer="друг" )
    card281 = Card(deckId=6, question="very", answer="очень" )
    card282 = Card(deckId=6, question="cat", answer="кот" )
    card283 = Card(deckId=6, question="who", answer="кто" )
    card284 = Card(deckId=6, question="son", answer="сын" )
    card285 = Card(deckId=6, question="My name is", answer="меня зовут" )
    card286 = Card(deckId=6, question="or", answer="или" )
    card287 = Card(deckId=6, question="three", answer="три" )
    card288 = Card(deckId=6, question="after", answer="после" )
    card289 = Card(deckId=6, question="to know", answer="знать" )
    card290 = Card(deckId=6, question="to read", answer="читать" )
    card291 = Card(deckId=6, question="where", answer="где" )
    card292 = Card(deckId=6, question="when", answer="когда" )
    card293 = Card(deckId=6, question="6", answer="шесть" )
    card294 = Card(deckId=6, question="to want", answer="хотеть" )
    card295 = Card(deckId=6, question="to eat", answer="кушать" )
    card296 = Card(deckId=6, question="quickly, fast", answer="быстро" )
    card297 = Card(deckId=6, question="always", answer="всегда" )
    card298 = Card(deckId=6, question="bad", answer="плохо" )
    card299 = Card(deckId=6, question="hi", answer="Привет" )
    card300 = Card(deckId=6, question="parents", answer="родители" )
    card301 = Card(deckId=6, question="house, home", answer="дом" )
    card302 = Card(deckId=6, question="store", answer="магазин" )
    card303 = Card(deckId=6, question="big", answer="большой" )
    card304 = Card(deckId=6, question="thank you", answer="спасибо" )
    card305 = Card(deckId=6, question="American", answer="американец" )
    card306 = Card(deckId=6, question="to understand", answer="понимать" )
    card307 = Card(deckId=6, question="to like, to love", answer="любить" )
    card308 = Card(deckId=6, question="2", answer="два" )
    card309 = Card(deckId=6, question="what", answer="что" )
    card310 = Card(deckId=6, question="7", answer="семь" )
    card311 = Card(deckId=6, question="sometimes", answer="иногда" )
    card312 = Card(deckId=6, question="to live", answer="жи́ть" )
    card313 = Card(deckId=6, question="god", answer="бог" )
    card314 = Card(deckId=6, question="already", answer="ужé" )

    card315 = Card(deckId=7, question="plate/ dish", answer="plat" )
    card316 = Card(deckId=7, question="you like/love", answer="aimez" )
    card317 = Card(deckId=7, question="you hate/detest", answer="détestez" )
    card318 = Card(deckId=7, question="to cook", answer="faire la cuisine" )
    card319 = Card(deckId=7, question="to cook", answer="cuisiner" )
    card320 = Card(deckId=7, question="a recipe", answer="une recette" )
    card321 = Card(deckId=7, question="make/cook/prepare", answer="préparer" )
    card322 = Card(deckId=7, question="cook in the oven, frying pan, saucepan", answer="faire cuire au four, à la poêle, à la casserole" )
    card323 = Card(deckId=7, question="to brown/fry, to brown", answer="dorer, rissoler" )
    card324 = Card(deckId=7, question="to roast", answer="rôtir" )
    card325 = Card(deckId=7, question="simmer", answer="laisser mijoter" )
    card326 = Card(deckId=7, question="to flip (pancake), sauté, to fry", answer="faire sauter, sauté, frire" )
    card327 = Card(deckId=7, question="to brown", answer="faire revenir" )
    card328 = Card(deckId=7, question="to cut, mince, peel", answer="couper (un couteau), émincer, éplucher" )
    card329 = Card(deckId=7, question="to stir in/ mix in", answer="remuer (avec une cuillère)" )
    card330 = Card(deckId=7, question="beat/whisk", answer="battre" )
    card331 = Card(deckId=7, question="to pour", answer="verser" )
    card332 = Card(deckId=7, question="to add", answer="ajouter" )
    card333 = Card(deckId=7, question="to grind", answer="moudre" )
    card334 = Card(deckId=7, question="to season/ dress (salad)", answer="assaisonner" )
    card335 = Card(deckId=7, question="sprinkle", answer="saupoudrer" )
    card336 = Card(deckId=7, question="to taste/ try", answer="goûter" )
    card337 = Card(deckId=7, question="to serve", answer="servir" )
    card338 = Card(deckId=7, question="to soak up the sauce from", answer="saucer" )
    card339 = Card(deckId=7, question="to spread", answer="tartiner" )
    card340 = Card(deckId=7, question="a cook/chef (f)", answer="une cuisinière (f)" )
    card341 = Card(deckId=7, question="a cup", answer="une tasse" )
    card342 = Card(deckId=7, question="tablespoon", answer="une cuillère à soupe" )
    card343 = Card(deckId=7, question="teaspoon", answer="une cuillère à café" )
    card344 = Card(deckId=7, question="a fork", answer="une fourchette" )
    card345 = Card(deckId=7, question="catering/ fast food,", answer="la restauration/l'alimentation rapide" )
    card346 = Card(deckId=7, question="allergies", answer="allergies" )
    card347 = Card(deckId=7, question="food restrictions", answer="restrictions alimentaires" )
    card348 = Card(deckId=7, question="diet", answer="un régime" )
    card349 = Card(deckId=7, question="to lose weight", answer="maigrir" )
    card350 = Card(deckId=7, question="to be in shape, to be in good health", answer="être en forme/être en bonne santé" )

    card351 = Card(deckId=8, question="with", answer="مع" )
    card352 = Card(deckId=8, question="excellent", answer="ممتاز" )
    card353 = Card(deckId=8, question="hello", answer="مرحبا" )
    card354 = Card(deckId=8, question="yes", answer="نعم" )
    card355 = Card(deckId=8, question="we", answer="نحن" )
    card356 = Card(deckId=8, question="here", answer="هنا" )
    card357 = Card(deckId=8, question="I am here", answer="انا هنا" )
    card358 = Card(deckId=8, question="she", answer="هي" )
    card359 = Card(deckId=8, question="flower", answer="وَرَّدَ" )
    card360 = Card(deckId=8, question="or", answer="أو" )
    card361 = Card(deckId=8, question="duty, work", answer="واجب" )
    card362 = Card(deckId=8, question="and", answer="و" )
    card363 = Card(deckId=8, question="chicken", answer="دجاجة" )
    card364 = Card(deckId=8, question="marriage", answer="زواج" )
    card365 = Card(deckId=8, question="wife", answer="زوجة" )
    card366 = Card(deckId=8, question="husband", answer="زوج" )
    card367 = Card(deckId=8, question="thanks", answer="شكر" )
    card368 = Card(deckId=8, question="fish (plural)", answer="سمك" )
    card369 = Card(deckId=8, question="a fish", answer="سمكة" )
    card370 = Card(deckId=8, question="north", answer="شمال" )
    card371 = Card(deckId=8, question="camel", answer="جَمَل" )
    card372 = Card(deckId=8, question="elephant", answer="فيل" )
    card373 = Card(deckId=8, question="beans", answer="فول" )
    card374 = Card(deckId=8, question="horse", answer="حصان" )
    card375 = Card(deckId=8, question="horse", answer="فَرَس" )
    card376 = Card(deckId=8, question="coffee", answer="قهوة" )
    card377 = Card(deckId=8, question="rabbit", answer="ارنب" )
    card378 = Card(deckId=8, question="car", answer="سيارة" )
    card379 = Card(deckId=8, question="water", answer="ماء" )
    card380 = Card(deckId=8, question="lion", answer="اسد" )
    card381 = Card(deckId=8, question="cup", answer="كاس" )
    card382 = Card(deckId=8, question="door", answer="باب" )
    card383 = Card(deckId=8, question="fox", answer="ثعلب" )
    card384 = Card(deckId=8, question="triangle", answer="مُثلَّث" )
    card385 = Card(deckId=8, question="neighbor", answer="جارٌ" )
    card386 = Card(deckId=8, question="flag", answer="علم" )
    card387 = Card(deckId=8, question="tree", answer="شجرة" )
    card388 = Card(deckId=8, question="student", answer="طَالِبٌ" )
    card389 = Card(deckId=8, question="book", answer="كتاب" )
    card390 = Card(deckId=8, question="how", answer="كيف" )
    card391 = Card(deckId=8, question="every", answer="كلّ" )

    card392 = Card(deckId=9, question="What did you say?", answer="vad sa du" )
    card393 = Card(deckId=9, question="sorry", answer="förlåt" )
    card394 = Card(deckId=9, question="How are you?", answer="Hur är det?" )
    card395 = Card(deckId=9, question="I don't understand", answer="Jag förstår inte" )
    card396 = Card(deckId=9, question="I don't know", answer="Jag vet inte" )
    card397 = Card(deckId=9, question="What do you mean?", answer="Vad menar du?" )
    card398 = Card(deckId=9, question="What does it mean?", answer="Vad betyder det?" )
    card399 = Card(deckId=9, question="How do you say that in Swedish?", answer="Vad heter det på svenska?" )
    card400 = Card(deckId=9, question="compare", answer="jämför" )
    card401 = Card(deckId=9, question="about", answer="om" )
    card402 = Card(deckId=9, question="spell", answer="stavar" )
    card403 = Card(deckId=9, question="pronunciation", answer="uttal, ett" )
    card404 = Card(deckId=9, question="vowels", answer="vokaler" )
    card405 = Card(deckId=9, question="lesson", answer="lektion (-en, -er, -erna)" )
    card406 = Card(deckId=9, question="read/study", answer="läser" )
    card407 = Card(deckId=9, question="study (informal)", answer="pluggar" )
    card408 = Card(deckId=9, question="call/ring", answer="ringer" )
    card409 = Card(deckId=9, question="fun", answer="roligt" )
    card410 = Card(deckId=9, question="sleep", answer="sover" )
    card411 = Card(deckId=9, question="study", answer="studerar" )
    card412 = Card(deckId=9, question="lecture hall", answer="hörsal" )
    card413 = Card(deckId=9, question="it's been a long time", answer="Det var länge sedan/sen" )
    card414 = Card(deckId=9, question="How's it going?", answer="Hur är läget?" )
    card415 = Card(deckId=9, question="oh yes", answer="jodå" )
    card416 = Card(deckId=9, question="How about you?", answer="Själv då? / och själv?" )
    card417 = Card(deckId=9, question="What about you?", answer="Du då?" )
    card418 = Card(deckId=9, question="so-so. I don't feel well", answer="sådär. jag mår inte bra" )
    card419 = Card(deckId=9, question="that's sad to hear", answer="det var tråkigt att höra" )
    card420 = Card(deckId=9, question="Its fine", answer="Det är lugnt." )
    card421 = Card(deckId=9, question="not so good", answer="inget vidare" )
    card422 = Card(deckId=9, question="not so good", answer="inte så bra" )
    card423 = Card(deckId=9, question="I have a cold", answer="Jag är förkyld" )
    card424 = Card(deckId=9, question="good to hear", answer="Skönt att höra!" )


    db.session.add(card001)
    db.session.add(card002)
    db.session.add(card003)
    db.session.add(card004)
    db.session.add(card005)
    db.session.add(card006)
    db.session.add(card007)
    db.session.add(card008)
    db.session.add(card009)
    db.session.add(card010)
    db.session.add(card011)
    db.session.add(card012)
    db.session.add(card013)
    db.session.add(card014)

    db.session.add(card015)
    db.session.add(card016)
    db.session.add(card017)
    db.session.add(card018)
    db.session.add(card019)
    db.session.add(card020)
    db.session.add(card021)
    db.session.add(card022)
    db.session.add(card023)
    db.session.add(card024)
    db.session.add(card025)
    db.session.add(card026)
    db.session.add(card027)
    db.session.add(card028)
    db.session.add(card029)
    db.session.add(card030)
    db.session.add(card031)
    db.session.add(card032)
    db.session.add(card033)
    db.session.add(card034)
    db.session.add(card035)
    db.session.add(card036)
    db.session.add(card037)
    db.session.add(card038)
    db.session.add(card039)
    db.session.add(card040)
    db.session.add(card041)

    db.session.add(card042)
    db.session.add(card043)
    db.session.add(card044)
    db.session.add(card045)
    db.session.add(card046)
    db.session.add(card047)
    db.session.add(card048)
    db.session.add(card049)
    db.session.add(card050)
    db.session.add(card051)
    db.session.add(card052)
    db.session.add(card053)
    db.session.add(card054)
    db.session.add(card055)
    db.session.add(card056)
    db.session.add(card057)
    db.session.add(card058)
    db.session.add(card059)
    db.session.add(card060)
    db.session.add(card061)
    db.session.add(card062)
    db.session.add(card063)
    db.session.add(card064)
    db.session.add(card065)
    db.session.add(card066)
    db.session.add(card067)
    db.session.add(card068)
    db.session.add(card069)
    db.session.add(card070)

    db.session.add(card071)
    db.session.add(card072)
    db.session.add(card073)
    db.session.add(card074)
    db.session.add(card075)
    db.session.add(card076)
    db.session.add(card077)
    db.session.add(card078)
    db.session.add(card079)
    db.session.add(card080)
    db.session.add(card081)
    db.session.add(card082)
    db.session.add(card083)
    db.session.add(card084)
    db.session.add(card085)
    db.session.add(card086)
    db.session.add(card087)
    db.session.add(card088)
    db.session.add(card089)
    db.session.add(card090)
    db.session.add(card091)
    db.session.add(card092)
    db.session.add(card093)
    db.session.add(card094)
    db.session.add(card095)
    db.session.add(card096)
    db.session.add(card097)
    db.session.add(card098)
    db.session.add(card099)
    db.session.add(card100)
    db.session.add(card101)
    db.session.add(card102)
    db.session.add(card103)
    db.session.add(card104)
    db.session.add(card105)
    db.session.add(card106)
    db.session.add(card107)
    db.session.add(card108)
    db.session.add(card109)
    db.session.add(card110)
    db.session.add(card111)
    db.session.add(card112)
    db.session.add(card113)
    db.session.add(card114)
    db.session.add(card115)
    db.session.add(card116)
    db.session.add(card117)
    db.session.add(card118)
    db.session.add(card119)
    db.session.add(card120)
    db.session.add(card121)
    db.session.add(card122)
    db.session.add(card123)
    db.session.add(card124)
    db.session.add(card125)
    db.session.add(card126)
    db.session.add(card127)
    db.session.add(card128)
    db.session.add(card129)
    db.session.add(card130)
    db.session.add(card131)
    db.session.add(card132)
    db.session.add(card133)
    db.session.add(card134)
    db.session.add(card135)
    db.session.add(card136)
    db.session.add(card137)
    db.session.add(card138)
    db.session.add(card139)
    db.session.add(card140)
    db.session.add(card141)
    db.session.add(card142)
    db.session.add(card143)
    db.session.add(card144)
    db.session.add(card145)
    db.session.add(card146)
    db.session.add(card147)
    db.session.add(card148)
    db.session.add(card149)
    db.session.add(card150)
    db.session.add(card151)
    db.session.add(card152)
    db.session.add(card153)
    db.session.add(card154)
    db.session.add(card155)
    db.session.add(card156)
    db.session.add(card157)
    db.session.add(card158)
    db.session.add(card159)
    db.session.add(card160)
    db.session.add(card161)
    db.session.add(card162)
    db.session.add(card163)
    db.session.add(card164)
    db.session.add(card165)
    db.session.add(card166)
    db.session.add(card167)
    db.session.add(card168)
    db.session.add(card169)
    db.session.add(card170)
    db.session.add(card171)
    db.session.add(card172)
    db.session.add(card173)
    db.session.add(card174)
    db.session.add(card175)
    db.session.add(card176)
    db.session.add(card177)
    db.session.add(card178)
    db.session.add(card179)
    db.session.add(card180)
    db.session.add(card181)
    db.session.add(card182)
    db.session.add(card183)
    db.session.add(card184)
    db.session.add(card185)
    db.session.add(card186)
    db.session.add(card187)
    db.session.add(card188)
    db.session.add(card189)
    db.session.add(card190)
    db.session.add(card191)
    db.session.add(card192)
    db.session.add(card193)
    db.session.add(card194)
    db.session.add(card195)
    db.session.add(card196)
    db.session.add(card197)
    db.session.add(card198)
    db.session.add(card199)
    db.session.add(card200)
    db.session.add(card201)
    db.session.add(card202)
    db.session.add(card203)
    db.session.add(card204)
    db.session.add(card205)
    db.session.add(card206)
    db.session.add(card207)
    db.session.add(card208)
    db.session.add(card209)
    db.session.add(card210)
    db.session.add(card211)
    db.session.add(card212)
    db.session.add(card213)
    db.session.add(card214)
    db.session.add(card215)
    db.session.add(card216)
    db.session.add(card217)
    db.session.add(card218)
    db.session.add(card219)
    db.session.add(card220)
    db.session.add(card221)
    db.session.add(card222)
    db.session.add(card223)
    db.session.add(card224)
    db.session.add(card225)
    db.session.add(card226)
    db.session.add(card227)
    db.session.add(card228)
    db.session.add(card229)
    db.session.add(card230)
    db.session.add(card231)
    db.session.add(card232)
    db.session.add(card233)
    db.session.add(card234)
    db.session.add(card235)
    db.session.add(card236)
    db.session.add(card237)
    db.session.add(card238)
    db.session.add(card239)
    db.session.add(card240)
    db.session.add(card241)
    db.session.add(card242)
    db.session.add(card243)
    db.session.add(card244)
    db.session.add(card245)
    db.session.add(card246)
    db.session.add(card247)
    db.session.add(card248)
    db.session.add(card249)
    db.session.add(card250)

    db.session.add(card251)
    db.session.add(card252)
    db.session.add(card253)
    db.session.add(card254)
    db.session.add(card255)
    db.session.add(card256)
    db.session.add(card257)
    db.session.add(card258)
    db.session.add(card259)
    db.session.add(card260)
    db.session.add(card261)
    db.session.add(card262)
    db.session.add(card263)
    db.session.add(card264)
    db.session.add(card265)
    db.session.add(card266)
    db.session.add(card267)
    db.session.add(card268)
    db.session.add(card269)
    db.session.add(card270)
    db.session.add(card271)
    db.session.add(card272)
    db.session.add(card273)
    db.session.add(card274)

    db.session.add(card275)
    db.session.add(card276)
    db.session.add(card277)
    db.session.add(card278)
    db.session.add(card279)
    db.session.add(card280)
    db.session.add(card281)
    db.session.add(card282)
    db.session.add(card283)
    db.session.add(card284)
    db.session.add(card285)
    db.session.add(card286)
    db.session.add(card287)
    db.session.add(card288)
    db.session.add(card289)
    db.session.add(card290)
    db.session.add(card291)
    db.session.add(card292)
    db.session.add(card293)
    db.session.add(card294)
    db.session.add(card295)
    db.session.add(card296)
    db.session.add(card297)
    db.session.add(card298)
    db.session.add(card299)
    db.session.add(card300)
    db.session.add(card301)
    db.session.add(card302)
    db.session.add(card303)
    db.session.add(card304)
    db.session.add(card305)
    db.session.add(card306)
    db.session.add(card307)
    db.session.add(card308)
    db.session.add(card309)
    db.session.add(card310)
    db.session.add(card311)
    db.session.add(card312)
    db.session.add(card313)
    db.session.add(card314)

    db.session.add(card315)
    db.session.add(card316)
    db.session.add(card317)
    db.session.add(card318)
    db.session.add(card319)
    db.session.add(card320)
    db.session.add(card321)
    db.session.add(card322)
    db.session.add(card323)
    db.session.add(card324)
    db.session.add(card325)
    db.session.add(card326)
    db.session.add(card327)
    db.session.add(card328)
    db.session.add(card329)
    db.session.add(card330)
    db.session.add(card331)
    db.session.add(card332)
    db.session.add(card333)
    db.session.add(card334)
    db.session.add(card335)
    db.session.add(card336)
    db.session.add(card337)
    db.session.add(card338)
    db.session.add(card339)
    db.session.add(card340)
    db.session.add(card341)
    db.session.add(card342)
    db.session.add(card343)
    db.session.add(card344)
    db.session.add(card345)
    db.session.add(card346)
    db.session.add(card347)
    db.session.add(card348)
    db.session.add(card349)
    db.session.add(card350)

    db.session.add(card351)
    db.session.add(card352)
    db.session.add(card353)
    db.session.add(card354)
    db.session.add(card355)
    db.session.add(card356)
    db.session.add(card357)
    db.session.add(card358)
    db.session.add(card359)
    db.session.add(card360)
    db.session.add(card361)
    db.session.add(card362)
    db.session.add(card363)
    db.session.add(card364)
    db.session.add(card365)
    db.session.add(card366)
    db.session.add(card367)
    db.session.add(card368)
    db.session.add(card369)
    db.session.add(card370)
    db.session.add(card371)
    db.session.add(card372)
    db.session.add(card373)
    db.session.add(card374)
    db.session.add(card375)
    db.session.add(card376)
    db.session.add(card377)
    db.session.add(card378)
    db.session.add(card379)
    db.session.add(card380)
    db.session.add(card381)
    db.session.add(card382)
    db.session.add(card383)
    db.session.add(card384)
    db.session.add(card385)
    db.session.add(card386)
    db.session.add(card387)
    db.session.add(card388)
    db.session.add(card389)
    db.session.add(card390)
    db.session.add(card391)

    db.session.add(card392)
    db.session.add(card393)
    db.session.add(card394)
    db.session.add(card395)
    db.session.add(card396)
    db.session.add(card397)
    db.session.add(card398)
    db.session.add(card399)
    db.session.add(card400)
    db.session.add(card401)
    db.session.add(card402)
    db.session.add(card403)
    db.session.add(card404)
    db.session.add(card405)
    db.session.add(card406)
    db.session.add(card407)
    db.session.add(card408)
    db.session.add(card409)
    db.session.add(card410)
    db.session.add(card411)
    db.session.add(card412)
    db.session.add(card413)
    db.session.add(card414)
    db.session.add(card415)
    db.session.add(card416)
    db.session.add(card417)
    db.session.add(card418)
    db.session.add(card419)
    db.session.add(card420)
    db.session.add(card421)
    db.session.add(card422)
    db.session.add(card423)
    db.session.add(card424)


    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_cards():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.cards RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM cards"))
        
    db.session.commit()